name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t fastapi-health .

      - name: Push Docker Image
        run: docker tag fastapi-health ${{ secrets.DOCKER_USERNAME }}/fastapi-health:latest && docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-health:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-health:latest
            docker stop fastapi-health || true
            docker rm fastapi-health || true
            docker run -d -p 80:8000 --name fastapi-health ${{ secrets.DOCKER_USERNAME }}/fastapi-health:latest
